export const FlowState = Object.freeze({
  IDLE: "IDLE",
  CAPTURE_ORANGE_CREDENTIALS: "CAPTURE_ORANGE_CREDENTIALS",
  OPEN_ORANGE_LOGIN: "OPEN_ORANGE_LOGIN",
  AUTH_ORANGE: "AUTH_ORANGE",
  NAVIGATE_ORANGE_BILLING: "NAVIGATE_ORANGE_BILLING",
  DOWNLOAD_OR_SELECT_BILL: "DOWNLOAD_OR_SELECT_BILL",
  OPEN_NAVAN: "OPEN_NAVAN",
  WAIT_FOR_USER_GOOGLE_SSO: "WAIT_FOR_USER_GOOGLE_SSO",
  OPEN_LIQUID_HOME: "OPEN_LIQUID_HOME",
  CLICK_NEW_TRANSACTION: "CLICK_NEW_TRANSACTION",
  UPLOAD_DOCUMENT: "UPLOAD_DOCUMENT",
  REVIEW_AND_CONFIRM: "REVIEW_AND_CONFIRM",
  DONE: "DONE",
  FAILED: "FAILED"
});

export const FlowStatus = Object.freeze({
  STARTED: "started",
  SUCCESS: "success",
  RETRY: "retry",
  FAILED: "failed",
  WAITING_USER: "waiting_user"
});

export const MessageType = Object.freeze({
  START_FLOW: "START_FLOW",
  RESUME_FLOW: "RESUME_FLOW",
  GET_STATUS: "GET_STATUS",
  CHECK_UPDATES: "CHECK_UPDATES",
  FLOW_EVENT: "FLOW_EVENT",
  RUN_PROVIDER_ACTION: "RUN_PROVIDER_ACTION",
  RUN_ORANGE_ACTION: "RUN_ORANGE_ACTION",
  RUN_NAVAN_ACTION: "RUN_NAVAN_ACTION"
});

export const ErrorCode = Object.freeze({
  ORANGE_TAB_NOT_FOUND: "ORANGE_TAB_NOT_FOUND",
  NAVAN_TAB_NOT_FOUND: "NAVAN_TAB_NOT_FOUND",
  ORANGE_AUTH_FAILED: "ORANGE_AUTH_FAILED",
  ORANGE_BILL_NOT_FOUND: "ORANGE_BILL_NOT_FOUND",
  NAVAN_SESSION_MISSING: "NAVAN_SESSION_MISSING",
  NAVAN_NEW_TRANSACTION_NOT_FOUND: "NAVAN_NEW_TRANSACTION_NOT_FOUND",
  NAVAN_FORM_FILL_FAILED: "NAVAN_FORM_FILL_FAILED",
  NAVAN_UPLOAD_FAILED: "NAVAN_UPLOAD_FAILED",
  ACTION_TIMEOUT: "ACTION_TIMEOUT",
  UNKNOWN: "UNKNOWN"
});

export const TIMEOUTS_MS = Object.freeze({
  SHORT: 10_000,
  DEFAULT: 20_000,
  LONG: 45_000,
  INACTIVITY: 15 * 60_000
});

export const MAX_RETRIES = 2;
